### ISSUE TITLE
Files in build/ do not belong on github

### ISSUE THREAD

**Issue by bnmnetp** [barbarer/py4e-int#34]
Please do not commit files in the build folder to github.  It breaks the automated update.

**Comment by barbarer** [comment]
I am sorry, I didn't realize that I had.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
I am not seeing a build directory here at all.  Where do you see this?

**Comment by bnmnetp** [comment]
The issues date back to this commit:  f5fa9c6b3e59ec892416ebf3858d93c34e5ca02c

I think it is probably resolved now.

**Comment by barbarer** [comment]
Sorry about that.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by barbarer** [comment]
We will try not to do this.
